# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5f08b5a3d9a10b469b294942552c8477437f3a47340d1b2b4746e77f8cb9eee010174df5b09048148a022626b86a2326195a9cbd1691574fb131dc1295dfec3

test:
  secret_key_base: a51734f68d68aa834a24e8575d351e7744df9999b497dd81470c99f508b6d57bfdd8398024b110a2ac6bcd83862b3c7164cb7df6b3f26489386ee530f07ece35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
